// ##### extgen :: Auto-generated file do not edit!! #####

package ${YYAndroidPackageName};
import ${YYAndroidPackageName}.GMExtWire.GMFunction;
import ${YYAndroidPackageName}.GMExtWire.GMValue;
import ${YYAndroidPackageName}.enums.*;

public interface GMBluetoothInterface {
    public boolean bluetooth_initialize();
    public void bluetooth_shutdown();
    public boolean bluetooth_is_initialized();
    public int bluetooth_last_error_code();
    public String bluetooth_last_error_message();
    public boolean bluetooth_le_is_supported();
    public boolean bluetooth_classic_is_supported();
    public boolean bluetooth_classic_server_is_supported();
    public int bluetooth_permission_get_status();
    public int bluetooth_permission_request();
    public int bluetooth_le_scan_start(boolean active);
    public int bluetooth_le_scan_stop();
    public boolean bluetooth_le_scan_is_running();
    public int bluetooth_classic_scan_start();
    public int bluetooth_classic_scan_stop();
    public boolean bluetooth_classic_scan_is_running();
    public void bluetooth_device_clear();
    public int bluetooth_device_get_count();
    public long bluetooth_device_get_at(int index);
    public boolean bluetooth_device_is_valid(long device);
    public int bluetooth_device_get_transport(long device);
    public String bluetooth_device_get_id(long device);
    public String bluetooth_device_get_name(long device);
    public boolean bluetooth_device_has_address(long device);
    public String bluetooth_device_get_address(long device);
    public boolean bluetooth_device_has_rssi(long device);
    public int bluetooth_device_get_rssi(long device);
    public boolean bluetooth_device_is_connectable(long device);
    public long bluetooth_classic_connect(long device, String service_uuid, GMFunction callback);
    public int bluetooth_classic_disconnect(long connection);
    public boolean bluetooth_classic_connection_is_valid(long connection);
    public boolean bluetooth_classic_connection_is_connected(long connection);
    public long bluetooth_classic_connection_get_device(long connection);
    public int bluetooth_classic_receive_available(long connection);
    public int bluetooth_classic_send(long connection, java.nio.ByteBuffer data, int offset, int size);
    public int bluetooth_classic_receive(long connection, java.nio.ByteBuffer out_data, int offset, int max_size);
    public int bluetooth_classic_server_start(String name, String service_uuid);
    public int bluetooth_classic_server_stop();
    public boolean bluetooth_classic_server_is_running();
    public int bluetooth_classic_discoverable_start(int duration_seconds);
    public int bluetooth_classic_discoverable_stop();
    public boolean bluetooth_classic_discoverable_is_running();
    public int bluetooth_pair(long device, GMFunction callback);
    public boolean bluetooth_device_is_paired(long device);
    public long bluetooth_le_connect(long device, GMFunction callback);
    public int bluetooth_le_disconnect(long connection);
    public boolean bluetooth_le_connection_is_valid(long connection);
    public boolean bluetooth_le_connection_is_connected(long connection);
    public long bluetooth_le_connection_get_device(long connection);
    public int bluetooth_le_services_discover(long connection, GMFunction callback);
    public int bluetooth_le_service_get_count(long connection);
    public long bluetooth_le_service_get_at(long connection, int index);
    public String bluetooth_le_service_get_uuid(long service);
    public int bluetooth_le_characteristics_discover(long service, GMFunction callback);
    public int bluetooth_le_characteristic_get_count(long service);
    public long bluetooth_le_characteristic_get_at(long service, int index);
    public String bluetooth_le_characteristic_get_uuid(long characteristic);
    public int bluetooth_le_characteristic_get_properties(long characteristic);
    public int bluetooth_le_descriptors_discover(long characteristic, GMFunction callback);
    public int bluetooth_le_descriptor_get_count(long characteristic);
    public long bluetooth_le_descriptor_get_at(long characteristic, int index);
    public String bluetooth_le_descriptor_get_uuid(long descriptor);
    public int bluetooth_le_characteristic_read(long characteristic, GMFunction callback);
    public int bluetooth_le_characteristic_get_value(long characteristic, java.nio.ByteBuffer out_data, int offset, int max_size);
    public int bluetooth_le_characteristic_write(long characteristic, java.nio.ByteBuffer data, int offset, int size, int write_type, GMFunction callback);
    public int bluetooth_le_characteristic_subscribe(long characteristic, int mode, GMFunction callback);
    public int bluetooth_le_descriptor_read(long descriptor, GMFunction callback);
    public int bluetooth_le_descriptor_get_value(long descriptor, java.nio.ByteBuffer out_data, int offset, int max_size);
    public int bluetooth_le_descriptor_write(long descriptor, java.nio.ByteBuffer data, int offset, int size, GMFunction callback);
    public int bluetooth_le_advertise_start(String settings_json, String data_json, GMFunction callback);
    public int bluetooth_le_advertise_stop();
    public boolean bluetooth_le_advertise_is_running();
    public int bluetooth_le_server_start();
    public int bluetooth_le_server_stop();
    public boolean bluetooth_le_server_is_running();
    public int bluetooth_le_server_add_service(String service_json, GMFunction callback);
    public int bluetooth_le_server_clear_services();
    public int bluetooth_le_server_respond_read(int request_id, int error_code, java.nio.ByteBuffer data, int offset, int size);
    public int bluetooth_le_server_respond_write(int request_id, int error_code);
    public int bluetooth_le_server_write_request_get_value(int request_id, java.nio.ByteBuffer out_data, int offset, int max_size);
    public int bluetooth_le_server_notify_value(String service_uuid, String characteristic_uuid, long connection, java.nio.ByteBuffer data, int offset, int size);
    public boolean bluetooth_set_callback_device_found(GMFunction callback);
    public boolean bluetooth_remove_callback_device_found();
    public boolean bluetooth_set_callback_scan_stopped(GMFunction callback);
    public boolean bluetooth_remove_callback_scan_stopped();
    public boolean bluetooth_set_callback_classic_client_connected(GMFunction callback);
    public boolean bluetooth_remove_callback_classic_client_connected();
    public boolean bluetooth_set_callback_classic_data(GMFunction callback);
    public boolean bluetooth_remove_callback_classic_data();
    public boolean bluetooth_set_callback_classic_disconnected(GMFunction callback);
    public boolean bluetooth_remove_callback_classic_disconnected();
    public boolean bluetooth_set_callback_le_disconnected(GMFunction callback);
    public boolean bluetooth_remove_callback_le_disconnected();
    public boolean bluetooth_set_callback_le_characteristic_value_changed(GMFunction callback);
    public boolean bluetooth_remove_callback_le_characteristic_value_changed();
    public boolean bluetooth_set_callback_le_server_connection_state_changed(GMFunction callback);
    public boolean bluetooth_remove_callback_le_server_connection_state_changed();
    public boolean bluetooth_set_callback_le_server_read_request(GMFunction callback);
    public boolean bluetooth_remove_callback_le_server_read_request();
    public boolean bluetooth_set_callback_le_server_write_request(GMFunction callback);
    public boolean bluetooth_remove_callback_le_server_write_request();
}