// ##### extgen :: Auto-generated file do not edit!! #####

#pragma once
#include "core/GMExtUtils.h"

// Internal function used for fetching dispatched function calls to GML
GMEXPORT double __EXT_NATIVE__GMBluetooth_invocation_handler(char* __ret_buffer, double __ret_buffer_length);

// Internal function used for queueing buffers to native code
GMEXPORT double __EXT_NATIVE__GMBluetooth_queue_buffer(char* __arg_buffer, double __arg_buffer_length);

GMEXPORT double __EXT_NATIVE__bluetooth_initialize();
GMEXPORT double __EXT_NATIVE__bluetooth_shutdown();
GMEXPORT double __EXT_NATIVE__bluetooth_is_initialized();
GMEXPORT double __EXT_NATIVE__bluetooth_last_error_code();
GMEXPORT char* __EXT_NATIVE__bluetooth_last_error_message();
GMEXPORT double __EXT_NATIVE__bluetooth_le_is_supported();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_is_supported();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_server_is_supported();
GMEXPORT double __EXT_NATIVE__bluetooth_permission_get_status();
GMEXPORT double __EXT_NATIVE__bluetooth_permission_request();
GMEXPORT double __EXT_NATIVE__bluetooth_le_scan_start(double active);
GMEXPORT double __EXT_NATIVE__bluetooth_le_scan_stop();
GMEXPORT double __EXT_NATIVE__bluetooth_le_scan_is_running();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_scan_start();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_scan_stop();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_scan_is_running();
GMEXPORT double __EXT_NATIVE__bluetooth_device_clear();
GMEXPORT double __EXT_NATIVE__bluetooth_device_get_count();
GMEXPORT double __EXT_NATIVE__bluetooth_device_get_at(double index, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_device_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_device_get_transport(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__bluetooth_device_get_id(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__bluetooth_device_get_name(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_device_has_address(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT char* __EXT_NATIVE__bluetooth_device_get_address(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_device_has_rssi(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_device_get_rssi(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_device_is_connectable(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_connect(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_disconnect(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_connection_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_connection_is_connected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_connection_get_device(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_receive_available(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_send(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_receive(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_server_start(char* name, char* service_uuid);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_server_stop();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_server_is_running();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_discoverable_start(double duration_seconds);
GMEXPORT double __EXT_NATIVE__bluetooth_classic_discoverable_stop();
GMEXPORT double __EXT_NATIVE__bluetooth_classic_discoverable_is_running();
GMEXPORT double __EXT_NATIVE__bluetooth_le_connect(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_disconnect(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_connection_is_valid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_connection_is_connected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_connection_get_device(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_services_discover(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_service_get_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_service_get_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__bluetooth_le_service_get_uuid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristics_discover(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_get_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_get_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__bluetooth_le_characteristic_get_uuid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_get_properties(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_descriptors_discover(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_descriptor_get_count(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_descriptor_get_at(char* __arg_buffer, double __arg_buffer_length, char* __ret_buffer, double __ret_buffer_length);
GMEXPORT char* __EXT_NATIVE__bluetooth_le_descriptor_get_uuid(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_read(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_get_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_write(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_characteristic_subscribe(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_descriptor_read(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_descriptor_get_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_descriptor_write(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_advertise_start(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_advertise_stop();
GMEXPORT double __EXT_NATIVE__bluetooth_le_advertise_is_running();
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_start();
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_stop();
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_is_running();
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_add_service(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_clear_services();
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_respond_read(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_respond_write(double request_id, double error_code);
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_write_request_get_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_le_server_notify_value(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_device_found(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_device_found();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_scan_stopped(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_scan_stopped();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_classic_client_connected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_classic_client_connected();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_classic_data(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_classic_data();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_classic_disconnected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_classic_disconnected();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_le_disconnected(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_le_disconnected();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_le_characteristic_value_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_le_characteristic_value_changed();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_le_server_connection_state_changed(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_le_server_connection_state_changed();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_le_server_read_request(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_le_server_read_request();
GMEXPORT double __EXT_NATIVE__bluetooth_set_callback_le_server_write_request(char* __arg_buffer, double __arg_buffer_length);
GMEXPORT double __EXT_NATIVE__bluetooth_remove_callback_le_server_write_request();

