// AUTOGENERATED - DO NOT EDIT
#include <jni.h>
#include <cstddef>
#include <algorithm>
#include <string>
#include "native/GMBluetoothInternal_exports.h"

// JNI requires global state because the VM reference must be captured at load time.
// JNI_OnLoad() is called when the shared library is loaded; we save the JavaVM pointer
// so that native threads can attach themselves later (see ScopedEnv below).
static JavaVM* g_vm = nullptr;

// Cached Java class/method references for callbacks into GML.
// These are resolved once at init time and reused (JNI method lookups are expensive).
static jclass g_bridgeClass = nullptr;
static jmethodID g_mid_GetExtensionOption = nullptr;

// JNI_OnLoad is called automatically when System.loadLibrary() occurs.
// This is our one chance to capture the VM pointer before any other JNI calls.
extern "C" jint JNI_OnLoad(JavaVM* vm, void*) { g_vm = vm; return JNI_VERSION_1_6; }

static void throwIAE(JNIEnv* env, const char* msg) {
    // FindClass aborts the process outright if an exception is already pending,
    // so log and clear whatever is in flight before raising our own.
    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
    }
    jclass iae = env->FindClass("java/lang/IllegalArgumentException");
    if (iae) env->ThrowNew(iae, msg);
}

// ScopedEnv: RAII wrapper for JNIEnv* that handles thread attachment.
// Native threads that weren't created by the JVM must call AttachCurrentThread
// before making any JNI calls. This struct does it automatically in ctor,
// and DetachCurrentThread in dtor. Main thread doesn't need attach (GetEnv succeeds).
struct ScopedEnv {
    JNIEnv* env = nullptr;
    bool detach = false;

    ScopedEnv() {
        if (!g_vm) return;
        jint rc = g_vm->GetEnv(reinterpret_cast<void**>(&env), JNI_VERSION_1_6);
        if (rc == JNI_OK) return;  // Already attached (main thread case)
        if (rc == JNI_EDETACHED && g_vm->AttachCurrentThread(&env, nullptr) == JNI_OK) {
            detach = true;  // We attached, so we must detach in dtor
        } else {
            env = nullptr;  // Failed to attach
        }
    }

    ~ScopedEnv() {
        if (detach) g_vm->DetachCurrentThread();
    }
};

// UtfChars: RAII wrapper for JNI string pinning.
// GetStringUTFChars returns a temporary C-string pointer that MUST be released
// via ReleaseStringUTFChars when done. This struct ensures proper cleanup.
// Without this, we'd leak JNI local refs and potentially crash on ref table overflow.
struct UtfChars {
    JNIEnv* env; jstring s; const char* p;
    UtfChars(JNIEnv* e, jstring js) : env(e), s(js), p(js ? e->GetStringUTFChars(js, nullptr) : nullptr) {}
    ~UtfChars() { if (s && p) env->ReleaseStringUTFChars(s, p); }
    const char* c_str() const { return p; }
};

static const char* __JNI_JAVA__GetExtensionOption(const char* extName, const char* optName)
{
    thread_local std::string tls_result;
    tls_result.clear();

    ScopedEnv scoped;
    if (!scoped.env || !g_bridgeClass || !g_mid_GetExtensionOption) {
        return nullptr;
    }

    JNIEnv* env = scoped.env;

    jstring jExtName = extName ? env->NewStringUTF(extName) : nullptr;
    jstring jOptName = optName ? env->NewStringUTF(optName) : nullptr;

    jstring jRet = static_cast<jstring>(
        env->CallStaticObjectMethod(g_bridgeClass, g_mid_GetExtensionOption, jExtName, jOptName)
    );

    if (jExtName) env->DeleteLocalRef(jExtName);
    if (jOptName) env->DeleteLocalRef(jOptName);

    if (env->ExceptionCheck()) {
        env->ExceptionDescribe();
        env->ExceptionClear();
        if (jRet) env->DeleteLocalRef(jRet);
        return nullptr;
    }

    if (!jRet) {
        return nullptr;
    }

    const char* chars = env->GetStringUTFChars(jRet, nullptr);
    if (!chars) {
        env->DeleteLocalRef(jRet);
        return nullptr;
    }

    tls_result.assign(chars);

    env->ReleaseStringUTFChars(jRet, chars);
    env->DeleteLocalRef(jRet);

    return tls_result.c_str();
}
static void __JNI_InitExtUtils()
{
    gm::details::GMRTRunnerInterface runner{};
    runner.ExtOptGetString = __JNI_JAVA__GetExtensionOption;
    gm::ExtUtils::Init(runner);
}
// __GMBluetooth_invocation_handler JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__GMBluetooth_invocation_handler(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__GMBluetooth_invocation_handler((char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}
// bluetooth_initialize JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_initialize_31278774638F(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_initialize();
    return static_cast<jdouble>(__ret);
}

// bluetooth_shutdown JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_shutdown_378D48E1C138(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_shutdown();
    return static_cast<jdouble>(__ret);
}

// bluetooth_update JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_update_3688EFA154F7(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_update();
    return static_cast<jdouble>(__ret);
}

// bluetooth_is_initialized JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_is_initialized_DA5CDAECAAC0(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_is_initialized();
    return static_cast<jdouble>(__ret);
}

// bluetooth_last_error_code JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_last_error_code_F0B596A6B55A(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_last_error_code();
    return static_cast<jdouble>(__ret);
}

// bluetooth_last_error_message JNI wrapper signature: ()Ljava/lang/String;
static jstring __JNI_WRAPPER__bluetooth_last_error_message_838BF9608693(JNIEnv* env, jclass /* GMBluetoothBridge */)
{
    const char* __out = __EXT_NATIVE__bluetooth_last_error_message();
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// bluetooth_le_is_supported JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_le_is_supported_DCB49501EB8B(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_le_is_supported();
    return static_cast<jdouble>(__ret);
}

// bluetooth_classic_is_supported JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_classic_is_supported_8C08342122F2(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_classic_is_supported();
    return static_cast<jdouble>(__ret);
}

// bluetooth_le_scan_start JNI wrapper signature: (D)D
static jdouble __JNI_WRAPPER__bluetooth_le_scan_start_1AE9D454FB1D(JNIEnv* /* env */, jclass /* GMBluetoothBridge */, jdouble active)
{
    double __ret = __EXT_NATIVE__bluetooth_le_scan_start(static_cast<double>(active));
    return static_cast<jdouble>(__ret);
}

// bluetooth_le_scan_stop JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_le_scan_stop_26B949DAA99B(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_le_scan_stop();
    return static_cast<jdouble>(__ret);
}

// bluetooth_le_scan_is_running JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_le_scan_is_running_9447537BE162(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_le_scan_is_running();
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_clear JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_device_clear_79019385A38F(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_device_clear();
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_get_count JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_device_get_count_86A7D6934F06(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_device_get_count();
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_get_at JNI wrapper signature: (DLjava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_get_at_8979E9445DD3(JNIEnv* env, jclass /* GMBluetoothBridge */, jdouble index, jobject __ret_buffer, jdouble __ret_buffer_length)
{
    void* __ret_buffer_ptr = env->GetDirectBufferAddress(__ret_buffer);
    jlong __ret_buffer_cap = env->GetDirectBufferCapacity(__ret_buffer);
    if (!__ret_buffer_ptr || __ret_buffer_cap <= 0) {
        throwIAE(env, "__ret_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_get_at(static_cast<double>(index), (char *)__ret_buffer_ptr, static_cast<double>(__ret_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_is_valid JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_is_valid_C4EE8447E8F5(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_is_valid((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_get_transport JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_get_transport_4A05945A72F3(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_get_transport((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_get_id JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__bluetooth_device_get_id_2147E16D9CB6(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__bluetooth_device_get_id((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// bluetooth_device_get_name JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__bluetooth_device_get_name_5A215822FA8B(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__bluetooth_device_get_name((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// bluetooth_device_has_address JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_has_address_49835C438B0B(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_has_address((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_get_address JNI wrapper signature: (Ljava/nio/ByteBuffer;D)Ljava/lang/String;
static jstring __JNI_WRAPPER__bluetooth_device_get_address_BE8D2E70CF88(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return nullptr;
    }
    const char* __out = __EXT_NATIVE__bluetooth_device_get_address((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    jstring __j = __out ? env->NewStringUTF(__out) : nullptr;
    return __j;
}

// bluetooth_device_has_rssi JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_has_rssi_C6880AF7571F(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_has_rssi((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_get_rssi JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_get_rssi_A437977AEF8C(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_get_rssi((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_device_is_connectable JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_device_is_connectable_F20DD641A8FD(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_device_is_connectable((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_set_callback_device_found JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_set_callback_device_found_A555A075C2AF(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_set_callback_device_found((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_remove_callback_device_found JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_remove_callback_device_found_9348AD38A881(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_remove_callback_device_found();
    return static_cast<jdouble>(__ret);
}

// bluetooth_set_callback_scan_stopped JNI wrapper signature: (Ljava/nio/ByteBuffer;D)D
static jdouble __JNI_WRAPPER__bluetooth_set_callback_scan_stopped_BCDC66A28F45(JNIEnv* env, jclass /* GMBluetoothBridge */, jobject __arg_buffer, jdouble __arg_buffer_length)
{
    void* __arg_buffer_ptr = env->GetDirectBufferAddress(__arg_buffer);
    jlong __arg_buffer_cap = env->GetDirectBufferCapacity(__arg_buffer);
    if (!__arg_buffer_ptr || __arg_buffer_cap <= 0) {
        throwIAE(env, "__arg_buffer must be a DIRECT ByteBuffer");
        return 0.0;
    }
    double __ret = __EXT_NATIVE__bluetooth_set_callback_scan_stopped((char *)__arg_buffer_ptr, static_cast<double>(__arg_buffer_length));
    return static_cast<jdouble>(__ret);
}

// bluetooth_remove_callback_scan_stopped JNI wrapper signature: ()D
static jdouble __JNI_WRAPPER__bluetooth_remove_callback_scan_stopped_66E80AC1F8D4(JNIEnv* /* env */, jclass /* GMBluetoothBridge */)
{
    double __ret = __EXT_NATIVE__bluetooth_remove_callback_scan_stopped();
    return static_cast<jdouble>(__ret);
}

// nativeRegister(Class callbackClass): cache callback + register all JNI wrappers
extern "C" {
    JNIEXPORT void JNICALL Java_com_gamemaker_ExtensionCore_ExtBridge_GMBluetoothBridge_nativeRegister(JNIEnv* env, jclass bridgeClass)
    {
        if (!g_bridgeClass) {
            g_bridgeClass = static_cast<jclass>(env->NewGlobalRef(bridgeClass));
        }

        if (!g_mid_GetExtensionOption) {
            g_mid_GetExtensionOption = env->GetStaticMethodID(
                g_bridgeClass,
                "__EXT_JAVA__GetExtensionOption",
                "(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;"
            );
            if (!g_mid_GetExtensionOption) {
                // Log and carry on: this runs from the bridge's <clinit>, so
                // throwing here becomes ExceptionInInitializerError and takes
                // the whole app down over a lookup helper. Extension options
                // just read back empty (see ExtUtils::GetExtensionOption).
                // The usual cause is R8 shrinking the method away -- the keep
                // rules live in ExtensionCore's <YYAndroidProguard> block.
                env->ExceptionDescribe();
                env->ExceptionClear();
            }
        }

        static bool g_extUtilsInitialized = false;
        if (!g_extUtilsInitialized) {
            __JNI_InitExtUtils();
            g_extUtilsInitialized = true;
        }

        // Registers all the native methods
        static const JNINativeMethod methods[] = {
            { "__EXT_JNI__GMBluetooth_invocation_handler", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__GMBluetooth_invocation_handler },
            { "__EXT_JNI__bluetooth_initialize", "()D", (void*)__JNI_WRAPPER__bluetooth_initialize_31278774638F },
            { "__EXT_JNI__bluetooth_shutdown", "()D", (void*)__JNI_WRAPPER__bluetooth_shutdown_378D48E1C138 },
            { "__EXT_JNI__bluetooth_update", "()D", (void*)__JNI_WRAPPER__bluetooth_update_3688EFA154F7 },
            { "__EXT_JNI__bluetooth_is_initialized", "()D", (void*)__JNI_WRAPPER__bluetooth_is_initialized_DA5CDAECAAC0 },
            { "__EXT_JNI__bluetooth_last_error_code", "()D", (void*)__JNI_WRAPPER__bluetooth_last_error_code_F0B596A6B55A },
            { "__EXT_JNI__bluetooth_last_error_message", "()Ljava/lang/String;", (void*)__JNI_WRAPPER__bluetooth_last_error_message_838BF9608693 },
            { "__EXT_JNI__bluetooth_le_is_supported", "()D", (void*)__JNI_WRAPPER__bluetooth_le_is_supported_DCB49501EB8B },
            { "__EXT_JNI__bluetooth_classic_is_supported", "()D", (void*)__JNI_WRAPPER__bluetooth_classic_is_supported_8C08342122F2 },
            { "__EXT_JNI__bluetooth_le_scan_start", "(D)D", (void*)__JNI_WRAPPER__bluetooth_le_scan_start_1AE9D454FB1D },
            { "__EXT_JNI__bluetooth_le_scan_stop", "()D", (void*)__JNI_WRAPPER__bluetooth_le_scan_stop_26B949DAA99B },
            { "__EXT_JNI__bluetooth_le_scan_is_running", "()D", (void*)__JNI_WRAPPER__bluetooth_le_scan_is_running_9447537BE162 },
            { "__EXT_JNI__bluetooth_device_clear", "()D", (void*)__JNI_WRAPPER__bluetooth_device_clear_79019385A38F },
            { "__EXT_JNI__bluetooth_device_get_count", "()D", (void*)__JNI_WRAPPER__bluetooth_device_get_count_86A7D6934F06 },
            { "__EXT_JNI__bluetooth_device_get_at", "(DLjava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_get_at_8979E9445DD3 },
            { "__EXT_JNI__bluetooth_device_is_valid", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_is_valid_C4EE8447E8F5 },
            { "__EXT_JNI__bluetooth_device_get_transport", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_get_transport_4A05945A72F3 },
            { "__EXT_JNI__bluetooth_device_get_id", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__bluetooth_device_get_id_2147E16D9CB6 },
            { "__EXT_JNI__bluetooth_device_get_name", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__bluetooth_device_get_name_5A215822FA8B },
            { "__EXT_JNI__bluetooth_device_has_address", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_has_address_49835C438B0B },
            { "__EXT_JNI__bluetooth_device_get_address", "(Ljava/nio/ByteBuffer;D)Ljava/lang/String;", (void*)__JNI_WRAPPER__bluetooth_device_get_address_BE8D2E70CF88 },
            { "__EXT_JNI__bluetooth_device_has_rssi", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_has_rssi_C6880AF7571F },
            { "__EXT_JNI__bluetooth_device_get_rssi", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_get_rssi_A437977AEF8C },
            { "__EXT_JNI__bluetooth_device_is_connectable", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_device_is_connectable_F20DD641A8FD },
            { "__EXT_JNI__bluetooth_set_callback_device_found", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_set_callback_device_found_A555A075C2AF },
            { "__EXT_JNI__bluetooth_remove_callback_device_found", "()D", (void*)__JNI_WRAPPER__bluetooth_remove_callback_device_found_9348AD38A881 },
            { "__EXT_JNI__bluetooth_set_callback_scan_stopped", "(Ljava/nio/ByteBuffer;D)D", (void*)__JNI_WRAPPER__bluetooth_set_callback_scan_stopped_BCDC66A28F45 },
            { "__EXT_JNI__bluetooth_remove_callback_scan_stopped", "()D", (void*)__JNI_WRAPPER__bluetooth_remove_callback_scan_stopped_66E80AC1F8D4 },
        };

        env->RegisterNatives(bridgeClass, methods, sizeof(methods)/sizeof(methods[0]));
    }
}
